#!/bin/bash

pamixer "$@"

printf -v vol '%3d' "$(pamixer --get-volume)"
out="$vol%"
[[ "$(pamixer --get-mute)" == 'true' ]] && ret='Mute'
dunstify -h string:x-dunst-stack-tag:vol -h "int:value:$vol" "Volume: $out"
