#!/bin/bash

[[ -z "$TMUX" ]] && command ssh "$@" && exit

for arg in "$@"; do
    [[ "$arg" =~ .*@.* ]] && title="$arg"
done

tmux rename-window "$title"
command ssh "$@"
tmux set-window-option automatic-rename "on" 1>/dev/null
