presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
shown_boxes = "proc net mem cpu"
update_ms = 1000
vim_keys = True
rounded_corners = True
force_tty = False
clock_format = "%y%m%d %H%M%S"
show_uptime = True
background_update = True
base_10_sizes = False
log_level = "WARNING"

color_theme = "/Users/dcairnshowarth/.config/btop/themes/dairnarth.theme"
theme_background = False
truecolor = True

graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"

proc_sorting = "cpu direct"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
proc_info_smaps = False
proc_left = False
proc_filter_kernel = False
proc_aggregate = True

custom_cpu_name = ""
cpu_graph_upper = "user"
cpu_graph_lower = "system"
cpu_invert_lower = True
cpu_single_graph = False
cpu_bottom = False
cpu_sensor = "Auto"
cpu_core_map = ""
show_cpu_freq = True

check_temp = True
show_coretemp = True
temp_scale = "celsius"

mem_graphs = False
mem_below_net = False
show_swap = True

disks_filter = ""
zfs_arc_cached = True
swap_disk = True
show_disks = True
only_physical = True
use_fstab = True
zfs_hide_datasets = False
disk_free_priv = False
show_io_stat = True
io_mode = False
io_graph_combined = False
io_graph_speeds = ""

net_download = 100
net_upload = 100
net_auto = True
net_sync = True
net_iface = ""

show_battery = True
selected_battery = "Auto"
show_battery_watts = True
